name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Download Tailwind CSS
      run: |
        curl --fail --location -o /tmp/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
        chmod +x /tmp/tailwindcss
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Hub - Build Tailwind CSS
      working-directory: ./LakeHub
      run: /tmp/tailwindcss build -i ./wwwroot/css/site.css -o ./wwwroot/css/output.css --minify
    - name: Hub - Build the Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./LakeHub/Dockerfile
        tags: ghcr.io/lakelink/hub:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/lakelink/hub:latest
        cache-to: type=inline

  build-cas2discourse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Download Tailwind CSS
      run: |
        curl --fail --location -o /tmp/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
        chmod +x /tmp/tailwindcss
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cas2Discourse - Build Tailwind CSS
      working-directory: ./Cas2Discourse
      run: /tmp/tailwindcss build -i ./wwwroot/css/site.css -o ./wwwroot/css/output.css --minify
    - name: Cas2Discourse - Build the Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Cas2Discourse/Dockerfile
        tags: ghcr.io/lakelink/cas2discourse:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/lakelink/cas2discourse:latest
        cache-to: type=inline
