name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Build Tailwind CSS
      working-directory: ./LakeHub
      run: |
        curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
        chmod +x tailwindcss-linux-x64
        ./tailwindcss-linux-x64 build -i ./wwwroot/css/site.css -o ./wwwroot/css/output.css --minify
        rm ./tailwindcss-linux-x64
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./LakeHub/Dockerfile
        tags: ghcr.io/lakelink/hub:latest
        push: true
        cache-from: type=registry,ref=ghcr.io/lakelink/overleaf-ldap-oauth2:latest
        cache-to: type=inline
